name: Add To GitHub projects
  
on:
  issues:
    types:
      - opened

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Run pre-commit
        uses: pre-commit/action@v2.0.3
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.4.0
        with:
          project-url: https://github.com/orgs/OpenPecha/projects/22
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
          labeled: bug
